language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

install:
  - composer install --no-progress --prefer-dist

script:
  - ./vendor/bin/phpunit
