language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    # test 2.7 LTS
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    # test 2.8 LTS
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    # test the latest stable 3.x release
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    # test the latest release (including beta releases)
    - php: 7.1
      env: DEPENDENCIES=beta

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit
