parameters:
    adback_api_client.command.refresh_tag.class: Adback\ApiClientBundle\Command\AnalyticsRefreshTagCommand

services:
    adback_api_client.command.refresh_tag:
        class: '%adback_api_client.command.refresh_tag.class%'
        arguments:
            - '@adback_api_client.query.script_url'
        tags:
            - { name: console.command }
            - { name: dekalee_nightly.task.strategy, priority: 100 }
