parameters:
    adback_api_client.command.refresh_tag.class: Adback\ApiClientBundle\Command\AnalyticsRefreshTagCommand

services:
    adback_api_client.command.refresh_tag:
        class: '%adback_api_client.command.refresh_tag.class%'
        calls:
            - method: setContainer
              arguments:
                  - '@service_container'
        tags:
            - { name: console.command }
            - { name: dekalee_nightly.task.strategy, priority: 100 }
