parameters:
    adback_api_client.config_file_script_cache.class: Adback\ApiClientBundle\Driver\ConfigFileScriptCache
    adback_api_client.cache_warmer.config_file.class: Adback\ApiClientBundle\CacheWarmer\ConfigFileCacheWarmer

services:
    adback_api_client.script_cache:
        class: '%adback_api_client.config_file_script_cache.class%'
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
    adback_api_client.cache_warmer.config_file:
        class: '%adback_api_client.cache_warmer.config_file.class%'
        arguments:
            - '@adback_api_client.query.script_url'
        tags:
            - { name: 'kernel.cache_warmer' }
