parameters:
    adback_api_client.doctrine_script_cache.class: Adback\ApiClientBundle\Driver\DoctrineScriptCache
    adback_api_client.repository.api_cache.class: Adback\ApiClientBundle\Repository\ApiCacheRepository
    adback_api_client.entity.api_cache.class: Adback\ApiClientBundle\Entity\ApiCache

services:
    adback_api_client.script_cache:
        class: '%adback_api_client.doctrine_script_cache.class%'
        arguments:
            - '@adback_api_client.repository.api_cache'
            - '@adback_api_client.orm.entity_manager'
    adback_api_client.repository.api_cache:
        class: '%adback_api_client.repository.api_cache.class%'
        factory: ['@adback_api_client.orm.entity_manager', getRepository]
        arguments:
            - '%adback_api_client.entity.api_cache.class%'
