parameters:
    dekalee_adback_analytics.doctrine_script_cache.class: Adback\ApiClientBundle\Driver\DoctrineScriptCache
    dekalee_adback_analytics.repository.api_cache.class: Adback\ApiClientBundle\Repository\ApiCacheRepository
    dekalee_adback_analytics.entity.api_cache.class: Adback\ApiClientBundle\Entity\ApiCache

services:
    dekalee_adback_analytics.script_cache:
        class: '%dekalee_adback_analytics.doctrine_script_cache.class%'
        arguments:
            - '@dekalee_adback_analytics.repository.api_cache'
            - '@dekalee_adback_analytics.orm.entity_manager'
    dekalee_adback_analytics.repository.api_cache:
        class: '%dekalee_adback_analytics.repository.api_cache.class%'
        factory: ['@dekalee_adback_analytics.orm.entity_manager', getRepository]
        arguments:
            - '%dekalee_adback_analytics.entity.api_cache.class%'
