parameters:
    adback_api_client.query.script_url.class: Adback\ApiClient\Query\FullScriptQuery

services:
    adback_api_client.query.script_url:
        class: '%adback_api_client.query.script_url.class%'
        arguments:
            - '@adback_api_client.client'
            - '@adback_api_client.script_cache'
            - '%adback_api_client.api.access_token%'
            - '%adback_api_client.api.api_url%'
        public: true
