parameters:
    dekalee_adback_analytics.redis_script_cache.class: Adback\ApiClient\Driver\RedisScriptCache

services:
    dekalee_adback_analytics.script_cache:
        class: '%dekalee_adback_analytics.redis_script_cache.class%'
        arguments:
            - '@dekalee_adback_analytics.cache'
