parameters:
    adback_api_client.redis_script_cache.class: Adback\ApiClient\Driver\RedisScriptCache

services:
    adback_api_client.script_cache:
        class: '%adback_api_client.redis_script_cache.class%'
        arguments:
            - '@adback_api_client.cache'
