parameters:
    adback_api_client.generator.analytics.class: Adback\ApiClient\Generator\AnalyticsScriptGenerator
    adback_api_client.generator.message.class: Adback\ApiClient\Generator\MessageScriptGenerator
    adback_api_client.generator.autopromo_banner.class: Adback\ApiClient\Generator\AutopromoBannerScriptGenerator
    adback_api_client.generator.product.class: Adback\ApiClient\Generator\ProductScriptGenerator
    adback_api_client.generator.iab.class: Adback\ApiClient\Generator\IabBannerScriptGenerator

services:
    adback_api_client.generator.analytics:
        class: '%adback_api_client.generator.analytics.class%'
        arguments:
            - '@adback_api_client.script_cache'
    adback_api_client.generator.message:
        class: '%adback_api_client.generator.message.class%'
        arguments:
            - '@adback_api_client.script_cache'
    adback_api_client.generator.autopromo_banner:
        class: '%adback_api_client.generator.autopromo_banner.class%'
        arguments:
            - '@adback_api_client.script_cache'
    adback_api_client.generator.product:
        class: '%adback_api_client.generator.product.class%'
        arguments:
            - '@adback_api_client.script_cache'
    adback_api_client.generator.iab:
        class: '%adback_api_client.generator.iab.class%'
        arguments:
            - '@adback_api_client.script_cache'
