parameters:
    adback_api_client.extension.script.class: Adback\ApiClientBundle\Twig\ScriptExtension

services:
    adback_api_client.extension.script:
        class: '%adback_api_client.extension.script.class%'
        arguments:
            - '@adback_api_client.generator.analytics'
            - '@adback_api_client.generator.message'
            - '@adback_api_client.generator.autopromo_banner'
            - '@adback_api_client.generator.product'
        tags:
            - { name: twig.extension }
