parameters:
    dekalee_adback_analytics.config_file_script_cache.class: Dekalee\AdbackAnalyticsBundle\Driver\ConfigFileScriptCache

services:
    dekalee_adback_analytics.script_cache:
        class: '%dekalee_adback_analytics.config_file_script_cache.class%'
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
