parameters:
    dekalee_adback_analytics.doctrine_script_cache.class: Dekalee\AdbackAnalyticsBundle\Driver\DoctrineScriptCache

services:
    dekalee_adback_analytics.script_cache:
        class: '%dekalee_adback_analytics.doctrine_script_cache.class%'
        arguments:
            - '@dekalee_adback_analytics.repository.api_cache'
            - '@dekalee_adback_analytics.orm.entity_manager'
