parameters:
    dekalee_adback_analytics.generator.analytics.class: Dekalee\AdbackAnalytics\Generator\AnalyticsScriptGenerator
    dekalee_adback_analytics.generator.message.class: Dekalee\AdbackAnalytics\Generator\MessageScriptGenerator
    dekalee_adback_autopromo_banner.generator.message.class: Dekalee\AdbackAnalytics\Generator\AutopromoBannerScriptGenerator

services:
    dekalee_adback_analytics.generator.analytics:
        class: '%dekalee_adback_analytics.generator.analytics.class%'
        arguments:
            - '@dekalee_adback_analytics.script_cache'
    dekalee_adback_analytics.generator.message:
        class: '%dekalee_adback_analytics.generator.message.class%'
        arguments:
            - '@dekalee_adback_analytics.script_cache'
    dekalee_adback_autopromo_banner.generator.message:
        class: '%dekalee_adback_autopromo_banner.generator.message.class%'
        arguments:
            - '@dekalee_adback_analytics.script_cache'
