parameters:
    dekalee_adback_analytics.extension.script.class: Dekalee\AdbackAnalyticsBundle\Twig\ScriptExtension

services:
    dekalee_adback_analytics.extension.script:
        class: '%dekalee_adback_analytics.extension.script.class%'
        arguments:
            - '@dekalee_adback_analytics.generator.analytics'
            - '@dekalee_adback_analytics.generator.message'
            - '@dekalee_adback_autopromo_banner.generator.message'
        tags:
            - { name: twig.extension }
